### PR TITLE
Job manager

### PR DESCRIPTION
**Pull request by holzworthd-agr**
Initialisation pull request.

### CODE REVIEW

**Comment by hol353** [comment]
I think you can get rid of everything under Packages and ParallelAPSIM.Tests/obj directories.

**Comment by holzworthd-agr** [comment]
Fixed. Not sure if I should tell it to ignore ParallelAPSIM.Tests/bin as well, but since there's nothing in there (for now), I'll leave it.

It compiles but will not run (due to not having any credentials to use)

**Comment by hol353** [comment]
I can still see the packages folder and the ParallelAPSIM.Tests/obj folder

**Comment by hol430** [comment]
This pull should probably be closed. @hol353 Are you able to close it? I can't since I didn't create it.

**Comment by hol353** [comment]
Ahh OK. Ignore my previous email.

**Comment by hol430** [comment]
Ok, thanks.

**Pull request closed without merging**
